version: '3.0'

services:
  app:
    image: golang:latest
    volumes:
      - '.:/home/app:ro'
      - './db:/db'
      - './cache:/go'
    environment:
      - DB_PATH=/db/event.db
    working_dir: '/home/app'
    ports:
      - 8080:8080
    command: sh -c "./event_tracker"
  caddy:
    image: caddy:latest
    volumes:
      - './Caddyfile:/etc/caddy/Caddyfile:ro'
    ports:
      - 443:443
