version: '3.0'

services:
  app:
    image: golang:latest
    volumes:
      - '.:/home/app:ro'
      - './db:/db'
    environment:
      - DB_PATH=/db/event.db
    working_dir: '/home/app'
    ports:
      - 80:8080
    command: sh -c "./event_tracker"
  caddy:
    image: caddy:latest
    volumes:
      - './caddy/Caddyfile:/etc/caddy/Caddyfile:ro'
      - './caddy/data:/data'
      - './caddy/config:/config'
    ports:
      - 443:443
  db:
    image: postgres:latest
    volumes:
      - './db:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=event_tracker
      - POSTGRES_USER=event_tracker
      - POSTGRES_DB=db
